-- REAL TIME SCENARIOS ---

-- SCENARIO 1 [ FINDING THE NTH VALUE ]
-- Q. MANAGER: I WANT 5TH MOST EXPENSIVE PRODUCT IN OUR COMPANY ?

SELECT * FROM dim_product;

WITH CTE_TABLE AS
(
SELECT
	UNIT_PRICE,
    product_name,
    DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE DESC) AS DENSE
FROM dim_product
)
SELECT * FROM CTE_TABLE
WHERE 
	DENSE = 5;
	
-- SCENARIO 2 [REMOVING DUPLICATES]

-- THIS ARE DUPLICATED DATA
SELECT * FROM CUSTOMERS;
INSERT INTO CUSTOMERS 
VALUES
(301,'LAMBA','CC'),
(101,'LOVE','AA');

-- DO IT USING ROW_NUMBER
-- WE APPLY PARTITION ON PRIMARY KEY AND HERE PRIMARY KEY IS ID SO ALL UNIQUE DATA GET 1 AND DUPLICATE GET MORE THAN 1
-- DEDUPP :FOR DUPLICATE TERM

-- ANSWER

WITH CTE_TABLE AS
(
SELECT
	*,
    row_number() OVER (partition by ID ORDER BY EMAIL) AS RNO
FROM
	CUSTOMERS
)
SELECT * FROM CTE_TABLE
WHERE RNO = 1;
    
    
-- SCENARIO 3 [ LAG AND LEAD ]

CREATE TABLE WEATHER
(
	id int,
    temp float
);
INSERT INTO WEATHER
VALUES
(1,10),
(2,12),
(3,9),
(4,15),
(5,20),
(6,15),
(7,12);

SELECT
	*,
    LAG(TEMP,1,'NOT AVAILABLE') OVER(ORDER BY ID ASC) AS PREVIOUS_DAY_TEMP,
    LEAD(TEMP,1,'NOT AVAILABLE') OVER(ORDER BY ID ASC)  AS NEXT_DAY_TEMP
FROM
	WEATHER;





