-- STORED PROCEDURE

DELIMITER //
CREATE PROCEDURE FIRST_PROCEDURE(IN P_ID INT ,P_NAME CHAR(100),P_EMAIL CHAR(100))
BEGIN
	INSERT INTO CUSTOMERS
    VALUES
		(P_ID,P_NAME,P_EMAIL);
END //

DELIMITER ;

call ecom.FIRST_PROCEDURE(10, 'PP', 'PAP@GMAIL.COM');
call ecom.FIRST_PROCEDURE(11, 'PKP', 'PKAP@GMAIL.COM');

SELECT * FROM CUSTOMERS;