-- WINDOW FUNCTIONS ---
SELECT * FROM dim_product;

-- Q. AVERAGE OF UNIT PRICE?

-- USING AGGREGATE FUNCTION
SELECT AVG(UNIT_PRICE) AS AVGPRICE FROM dim_product;
-- AS AGGREGATE FUNCAATION SQUEEZE ALL ROWS AND SHOW ONLY THE REQUIRED ANSWER BUT I WANT IT SHOULD SHOULD AVERAGE IN THE MAIN TABLE IN EACH ROW

-- USING WINDOW FUNCTION
SELECT 
	*,
	SUM(UNIT_PRICE) OVER(ORDER BY UNIT_PRICE), -- running sum/running total
    AVG(UNIT_PRICE) OVER(ORDER BY UNIT_PRICE), -- RUNNING AVERAGE
    SUM(UNIT_PRICE) OVER() AS TOTAL,
    SUM(UNIT_PRICE) OVER(ORDER BY LAUNCH_DATE) -- RUNNING TOTAL
FROM 
	DIM_PRODUCT;

-- 2 [FRAMES / MANIPULATING THE FRAMES OR WINDOW FUNCTIONS]
SELECT 
	*,
    SUM(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
FROM 
	DIM_PRODUCT;
-- 3 [TOTAL SUM]
SELECT
	*,
    SUM(UNIT_PRICE) OVER (ORDER BY LAUNCH_DATE ROWS BETWEEN unbounded preceding AND unbounded following)
FROM dim_product;


-- RANKING: WINDOW FUNCTIONS ---
-- 1 [ RANK() ]
SELECT
	UNIT_PRICE,
    RANK() OVER(ORDER BY UNIT_PRICE) AS 'RANK'
FROM
	DIM_PRODUCT;

-- 2 [ DENSE_RANK() ]
SELECT
	UNIT_PRICE,
    DENSE_RANK() OVER (ORDER BY UNIT_PRICE) AS 'DENSE RANK'
FROM 
	dim_product;

-- 3 [ROW_NUMBER()]
SELECT 
	UNIT_PRICE,
    ROW_NUMBER() OVER(ORDER BY UNIT_PRICE) AS ROW_NUM
FROM
	dim_product;

-- FOR PARTITION USING RANKING
SELECT 
	UNIT_PRICE,
    CATEGORY,
    ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE) AS ROW_NUM,
	RANK() OVER (PARTITION BY CATEGORY ORDER BY UNIT_PRICE) AS 'RANK',
    DENSE_RANK() OVER(partition by category ORDER BY UNIT_PRICE) AS 'DENSE_RANK'

FROM
	dim_product;



